repos:
-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    -   id: black
        args: [--safe]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: check-byte-order-marker
    - id: check-executables-have-shebangs
    - id: check-merge-conflict
    - id: check-yaml
    - id: debug-statements
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: trailing-whitespace
- repo: https://gitlab.com/pycqa/flake8.git
  rev: 3.8.3
  hooks:
  - id: flake8
    language_version: python3
    additional_dependencies:
    - flake8-2020>=1.6.0
    - flake8-docstrings>=1.5.0
    - flake8-pytest-style>=1.2.2
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.782
  hooks:
  - id: mypy
    # empty args needed in order to match mypy cli behavior
    args: []
    additional_dependencies:
    - Sphinx>=3.1.2
# - repo: https://github.com/pre-commit/mirrors-pylint
#   rev: v2.5.3
#   hooks:
#   - id: pylint
